djangoapp/blog/urls.py
from blog import views
from django.urls import path

app_name = "blog"

urlpatterns = [
    path("", views.index, name="index-blog"),
    path("post/<slug:slug>", views.post, name="post"),
    path("page/<slug:slug>", views.page, name="page"),
    path("created_by/<int:author_pk>", views.created_by, name="created_by"),
    path("category/<slug:slug>", views.category, name="category"),
    path("tag/<slug:slug>", views.tag, name="tag"),
    path("search/", views.search, name="search"),
]

djangoapp/project/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from project.language import set_language

urlpatterns = [
    path("", include("portfolio.urls")),
    path("blog/", include("blog.urls")),
    path("summernote/", include("django_summernote.urls")),
    path("admin/", admin.site.urls),
]

urlpatterns = [
    # Internacionalization
    *i18n_patterns(*urlpatterns, prefix_default_language=False),
    path("set_language/<str:language>", set_language, name="set-language"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoapp/blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django_summernote.models import AbstractAttachment
from utils.random_slug import slugify_new
from utils.resize_image import resize_image


class Tag(models.Model):
    class Meta:
        verbose_name = "Tag"
        verbose_name_plural = "Tags"

    name = models.CharField(max_length=255)
    slug = models.SlugField(
        unique=True,
        default=None,
        null=True,
        blank=True,
        max_length=255,
    )

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.name)
        return super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.name


class Category(models.Model):
    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    name = models.CharField(max_length=255)
    slug = models.SlugField(
        unique=True, default=None, null=True, blank=True, max_length=255
    )

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.name)
        return super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.name


class Page(models.Model):
    class Meta:
        verbose_name = "Page"
        verbose_name_plural = "Pages"

    title = models.CharField(max_length=65)
    slug = models.SlugField(
        unique=True, default=None, null=True, blank=True, max_length=255
    )
    is_published = models.BooleanField(
        default=False,
        help_text="This field will need to be checked for the page to be displayed",  # noqa 501
    )
    content = models.TextField()

    def get_absolute_url(self):
        if not self.is_published:
            return reverse("blog:index")
        return reverse("blog:page", args=(self.slug,))

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.title)
        return super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.title


class PostManager(models.Manager):
    def get_published(self):
        return self.filter(is_published=True).order_by("-pk")


class Post(models.Model):
    class Meta:
        verbose_name = "Post"
        verbose_name_plural = "Posts"

    objects = PostManager()

    title = models.CharField(max_length=65)
    slug = models.SlugField(
        unique=True, default=None, null=True, blank=True, max_length=255
    )
    is_published = models.BooleanField(
        default=False,
        help_text="This field will need to be checked for the post to be displayed",
    )
    excerpt = models.CharField(max_length=150)
    content = models.TextField()
    cover = models.ImageField(upload_to="posts/%Y/%m", blank=True, default="")
    cover_in_post_content = models.BooleanField(
        default=True,
        help_text="If checked, will display the cover within the post content",
    )

    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="post_created_by",
    )
    updated_at = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="post_updated_by",
    )

    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True, default=None
    )
    tags = models.ManyToManyField(Tag, blank=True, default="")

    def get_absolute_url(self):
        if not self.is_published:
            return reverse("blog:index")
        return reverse("blog:post", args=(self.slug,))

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.title)

        cover_name_before_save = str(self.cover.name)

        super_save = super().save(*args, **kwargs)

        cover_changed = False

        if self.cover:
            if cover_name_before_save != self.cover.name:
                cover_changed = True

        if cover_changed:
            resize_image(
                image=self.cover,
                new_width=900,
                optimize=True,
                quality=70,
            )

        return super_save

    def __str__(self) -> str:
        return self.title


class PostAttachment(AbstractAttachment):
    def save(self, *args, **kwargs):
        if not self.name:
            self.name = self.file.name
        file_name_before_save = str(self.file.name)

        super_save = super().save(*args, **kwargs)

        file_changed = False

        if self.file:
            if file_name_before_save != self.file.name:
                file_changed = True

        if file_changed:
            resize_image(
                image=self.file,
                new_width=900,
                optimize=True,
                quality=70,
            )

        return super_save

djangoapp/blog/views.py
from blog.models import Page, Post
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import Http404
from django.shortcuts import render

POSTS_PER_PAGE = 9


def index(request):
    posts = Post.objects.get_published()

    paginator = Paginator(posts, POSTS_PER_PAGE)
    page_number = request.GET.get("page")
    page_objs = paginator.get_page(page_number)

    page_title = "Home"
    context = {"page_objs": page_objs, "page_title": page_title}
    return render(request, "blog/index.html", context=context)


def created_by(request, author_pk):
    user_obj = User.objects.filter(pk=author_pk).first()
    if user_obj is None:
        raise Http404()

    author_full_name = user_obj.username
    if user_obj.first_name:
        author_full_name = f"{user_obj.first_name} {user_obj.last_name}"

    posts = Post.objects.get_published().filter(created_by__pk=author_pk)

    paginator = Paginator(posts, POSTS_PER_PAGE)
    page_number = request.GET.get("page")
    page_objs = paginator.get_page(page_number)

    page_title = f"Posts de {author_full_name}"
    context = {
        "page_objs": page_objs,
        "page_title": page_title,
    }
    return render(request, "blog/index.html", context=context)


def category(request, slug):
    posts = Post.objects.get_published().filter(category__slug=slug)

    paginator = Paginator(posts, POSTS_PER_PAGE)
    page_number = request.GET.get("page")
    page_objs = paginator.get_page(page_number)

    if len(posts) == 0:
        raise Http404()

    page_title = f"{page_objs[0].category.name} - Category"
    context = {
        "page_objs": page_objs,
        "page_title": page_title,
    }
    return render(request, "blog/index.html", context=context)


def tag(request, slug):
    posts = Post.objects.get_published().filter(tags__slug=slug)

    paginator = Paginator(posts, POSTS_PER_PAGE)
    page_number = request.GET.get("page")
    page_objs = paginator.get_page(page_number)

    if len(posts) == 0:
        raise Http404()

    page_title = page_objs[0].tags.filter(slug=slug).first().name
    context = {
        "page_objs": page_objs,
        "page_title": f"{page_title} - Tag",
    }
    return render(request, "blog/index.html", context=context)


def search(request):
    search_value = request.GET.get("search").strip()
    posts = Post.objects.get_published().filter(
        Q(title__icontains=search_value)
        | Q(excerpt__icontains=search_value)
        | Q(content__icontains=search_value)
    )[:POSTS_PER_PAGE]

    page_title = f"{search_value[:30]} - Search"
    context = {
        "page_objs": posts,
        "search_value": search_value,
        "page_title": page_title,
    }
    return render(request, "blog/index.html", context=context)


def page(request, slug):
    page_obj = Page.objects.filter(is_published=True, slug=slug).first()
    if page_obj is None:
        raise Http404()

    page_title = page_obj.title
    context = {"page": page_obj, "page_title": page_title}
    return render(request, "blog/page.html", context=context)


def post(request, slug):
    post_obj = Post.objects.get_published().filter(slug=slug).first()
    if post_obj is None:
        raise Http404()

    page_title = post_obj.title
    context = {"post": post_obj, "page_title": page_title}
    return render(request, "blog/post.html", context=context)

djangoapp/blog/templates/blog/index.html
{% extends 'global/blog/base.html' %}

{% block content %}
  <main class="main-content section-wrapper">
    <div class="section-content-wide">
      <div class="section-gap">

        {% if page_objs %}
          <div class="card-grid">
            {% for post in page_objs %}
              {% include 'blog/partials/_post-card.html' with i=forloop.counter0 %}
            {% endfor %}
          </div>
        {% else %}
          <div class="not-found center">
            <h1>Nothing found :c</h1>
            <p>
              I didn't find anything in this link, please try another link
              blog or go to <a href="{% url "blog:index-blog" %}">Home</a>
            </p>
          </div>
        {% endif %}

      </div>
    </div>
  </main>
{% endblock content %}

djangoapp/blog/templates/blog/page.html
{% extends 'blog/base.html' %}

{% block content %}
  <main class="main-content section-wrapper">
    <div class="section-content-narrow">
      <div class="section-gap">
        <h1 class="center">{{ page.title }}</h1>
        <p>{{ page.content | safe }}</p>
      </div>
    </div>
  </main>
{% endblock content %}

djangoapp/blog/templates/blog/post.html
{% extends 'global/blog/base.html' %}

{% block additional_head %}
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/codemirror.min.css">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/theme/dracula.min.css">

<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/codemirror.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/python/python.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/javascript/javascript.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/htmlmixed/htmlmixed.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/css/css.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/xml/xml.min.js"></script>
{% endblock additional_head %}

{% block content %}
<main class="main-content single-post section-wrapper">
  <div class="single-post-content section-content-narrow">
    <div class="single-post-gap section-gap">

      {% if post.cover and post.cover_in_post_content %}
        <div class="single-post-cover pb-base">
          <img loading="lazy" src="{{ post.cover.url }}" alt="Imagem do post {{ post.title }}">
        </div>
      {% endif %}

      <h2 class="single-post-title pb-base center">
        {{ post.title }}
      </h2>

      <div class="post-meta pb-base">
        <div class="post-meta-item">
          <a class="post-meta-link" href="{% url "blog:created_by" post.created_by.pk %}">
            <i class="fa-solid fa-user"></i>
            <span>
              {% if post.created_by.first_name %}
                {{ post.created_by.first_name }}
                {{ post.created_by.last_name }}
              {% else %}
                {{ post.created_by.username }}
              {% endif %}
            </span>
          </a>
        </div>
        <div class="post-meta-item">
          <span class="post-meta-link">
            <i class="fa-solid fa-calendar-days"></i>
            <span>
              {{ post.created_at | date:'m/Y' }}
              {% comment %} https://docs.djangoproject.com/en/4.2/ref/templates/builtins/#date {% endcomment %}
            </span>
          </span>
        </div>

        {% if post.category %}
          <div class="post-meta-item">
            <a class="post-meta-link" href="{% url "blog:category" post.category.slug %}">
              <i class="fa-solid fa-tag"></i>
              <span>
                {{ post.category.name }}
              </span>
            </a>
          </div>
        {% endif %}

      </div>

      <p class="single-post-excerpt pb-base">
        {{ post.excerpt | safe }}
        {% comment %} safe é utilizado para que seja possível renderizar html no conteúdo do excerpt {% endcomment %}
      </p>

      <div class="separator"></div>

      <div class="single-post-content">
        {{ post.content | safe }}
      
        <div class="post-tags">
          <span>Tags: </span>

          {% if post.tags.exists %}
            {% comment %}
              Em uma relação "many to many" não é possível realizar consultas com "if post.tags"
              É necessário utilizar o exists
            {% endcomment %}
            {% for tag in post.tags.all %}
              <a class="post-tag-link" href="{% url "blog:tag" tag.slug %}">
                <i class="fa-solid fa-link"></i>
                <span>{{ tag.name }}</span>
              </a>            
            {% endfor %}
          {% endif %}

        </div>
        
      </div>
    
    </div>
  </div>
</main>

{% endblock content %}